name: A-TO-B:MASTER
on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:
    inputs:
      env:
        description: environment
        default: dev
        required: true
jobs:
  set_env:
    outputs:
      env: ${{ steps.setenv.outputs.env }}
    runs-on: ubuntu-latest
    steps:
      - id: setenv
        run: |
          if test -n "${{ github.event.inputs.env }}"
          then
            echo "::set-output name=env::${{ github.event.inputs.env }}"
          fi
          if test "${{ github.event_name }}" = 'push' -a "${{ github.ref }}" = 'refs/heads/develop'
          then
            echo "::set-output name=env::dev"
          fi
          if test "${{ github.event_name }}" = 'push' -a "${{ github.ref }}" = 'refs/heads/main'
          then
            echo "::set-output name=env::prod"
          fi
  build-and-deploy:
    needs: set_env
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install and Build
        run: |
          yarn install
          yarn run docs:build
      - name: Copy 404.html
        run: |
          cp docs/.vuepress/dist/tidy3d/404.html docs/.vuepress/dist
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/.vuepress/dist
          token: ${{ secrets.KB_TOKEN }}
          repository-name: shmily1213866/kb-${{ needs.set_env.outputs.env }}
          clean-exclude: |
            /flow360
            /index.html
          single-commit: true
