name: A-TO-B:MASTER
on: [push]
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install and Build
        run: |
          yarn install
          yarn run docs:build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/.vuepress/dist
          branch: gh-pages
          repository-name: shmily1213866/kb
          target-folder: tidy3d
      # - name: Deploy
      #   uses: s0/git-publish-subdir-action@develop
      #   env:
      #     REPO: git@github.com:shmily1213866/kb.git
      #     BRANCH: gh-pages
      #     FOLDER: docs/.vuepress/dist
      #     TARGET_DIR: tidy3d
      #     SSH_PRIVATE_KEY: ${{ secrets.ID_RSA_KB }}
      #     SQUASH_HISTORY: true
