name: A-TO-B:MASTER
on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:
    inputs:
      env:
        description: environment
        default: dev
        required: true
jobs:
  set_repository_name:
    outputs:
      repository_name: ${{ steps.setrepositoryname.outputs.repository_name }}
    runs-on: ubuntu-latest
    steps:
      - id: setrepositoryname
        run: |
          if test "${{ github.event.inputs.env }}" = 'dev'
          then
            echo "::set-output name=repository_name::shmily1213866/kb-dev"
          fi
          if test "${{ github.event.inputs.env }}" = 'prod'
          then
            echo "::set-output name=repository_name::shmily1213866/kb"
          fi
          if test "${{ github.event_name }}" = 'push' -a "${{ github.ref }}" = 'refs/heads/develop'
          then
            echo "::set-output name=repository_name::shmily1213866/kb-dev"
          fi
          if test "${{ github.event_name }}" = 'push' -a "${{ github.ref }}" = 'refs/heads/main'
          then
            echo "::set-output name=repository_name::shmily1213866/kb"
          fi
  build-and-deploy:
    needs: set_repository_name
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install and Build
        run: |
          yarn install
          yarn run docs:build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/.vuepress/dist
          token: ${{ secrets.KB_TOKEN }}
          branch: main
          repository-name: ${{ needs.set_repository_name.outputs.repository_name }}
          target-folder: tidy3d
          single-commit: true
